export const meta = {
  dependencies: {},
  devDependencies: {},
  internalDependencies: [],
  tokens: [
    "--color-fm-contrast",
    "--color-fm-inactive",
    "--color-fm-primary",
    "--color-fm-secondary",
    "--color-fm-tertiary",
    "--font-fm-brand",
    "--font-fm-text",
    "--font-fm-toons",
    "--leading-fm-2xl",
    "--leading-fm-3xl",
    "--leading-fm-4xl",
    "--leading-fm-5xl",
    "--leading-fm-6xl",
    "--leading-fm-7xl",
    "--leading-fm-8xl",
    "--leading-fm-lg",
    "--leading-fm-md",
    "--leading-fm-sm",
    "--leading-fm-xl",
    "--leading-fm-xs",
    "--text-fm-2xl",
    "--text-fm-3xl",
    "--text-fm-4xl",
    "--text-fm-5xl",
    "--text-fm-6xl",
    "--text-fm-7xl",
    "--text-fm-8xl",
    "--text-fm-lg",
    "--text-fm-md",
    "--text-fm-sm",
    "--text-fm-xl",
    "--text-fm-xs",
  ],
}
