export const meta = {
  dependencies: {},
  devDependencies: {},
  internalDependencies: ["feature-shine-icon"],
  tokens: [
    "--color-fm-contrast",
    "--color-fm-electricblue-1000",
    "--color-fm-electricblue-200",
    "--color-fm-emerald-100",
    "--color-fm-emerald-900",
    "--color-fm-hotpink-100",
    "--color-fm-hotpink-900",
    "--color-fm-info",
    "--color-fm-info-sec",
    "--color-fm-lemon-100",
    "--color-fm-lemon-900",
    "--color-fm-negative",
    "--color-fm-negative-tert",
    "--color-fm-neongreen-100",
    "--color-fm-neongreen-900",
    "--color-fm-positive",
    "--color-fm-positive-sec",
    "--color-fm-primary",
    "--color-fm-secondary",
    "--color-fm-surface-electricblue",
    "--color-fm-surface-emerald",
    "--color-fm-surface-hotpink",
    "--color-fm-surface-info",
    "--color-fm-surface-info-sec",
    "--color-fm-surface-lemon",
    "--color-fm-surface-negative",
    "--color-fm-surface-negative-sec",
    "--color-fm-surface-neongreen",
    "--color-fm-surface-positive",
    "--color-fm-surface-positive-sec",
    "--color-fm-surface-secondary",
    "--color-fm-surface-warning",
    "--color-fm-tag-electricblue",
    "--color-fm-tag-emerald",
    "--color-fm-tag-hotpink",
    "--color-fm-tag-lemon",
    "--color-fm-tag-neongreen",
    "--color-fm-warning",
    "--color-fm-yellow-200",
    "--color-fm-yellow-900",
    "--font-fm-brand",
    "--spacing-fm-lg",
    "--spacing-fm-md",
    "--text-fm-md",
    "--text-fm-sm",
  ],
}
