export const meta = {
  dependencies: {},
  devDependencies: {},
  internalDependencies: [
    "use-standalone-pagination",
    "chevron-double-left-icon",
    "chevron-double-right-icon",
    "chevron-left-icon",
    "chevron-right-icon",
    "select",
  ],
  tokens: [
    "--color-fm-contrast",
    "--color-fm-divider-contrast",
    "--color-fm-divider-tertiary",
    "--color-fm-inactive",
    "--color-fm-primary",
    "--color-fm-surface-contrast",
    "--color-fm-surface-primary",
    "--color-fm-tertiary",
    "--leading-fm-lg",
    "--leading-fm-md",
    "--leading-fm-sm",
    "--radius-fm-s",
    "--text-fm-lg",
    "--text-fm-md",
    "--text-fm-sm",
  ],
}
