export const meta = {
  dependencies: {},
  devDependencies: {},
  internalDependencies: ["feature-shine-icon", "arrow-right-icon"],
  tokens: [
    "--color-fm-divider-secondary",
    "--color-fm-info-sec",
    "--color-fm-info-tert",
    "--color-fm-negative-sec",
    "--color-fm-negative-tert",
    "--color-fm-positive-sec",
    "--color-fm-positive-tert",
    "--color-fm-surface-info",
    "--color-fm-surface-negative",
    "--color-fm-surface-positive",
    "--color-fm-surface-secondary",
    "--color-fm-surface-warning",
    "--color-fm-warning-sec",
    "--color-fm-warning-tert",
    "--font-fm-text",
    "--gradient-fm-banner-info",
    "--gradient-fm-banner-negative",
    "--gradient-fm-banner-positive",
    "--gradient-fm-banner-warning",
    "--gradient-fm-stroke-info",
    "--gradient-fm-stroke-negative",
    "--gradient-fm-stroke-positive",
    "--gradient-fm-stroke-warning",
    "--leading-fm-lg",
    "--leading-fm-sm",
    "--radius-fm-s",
    "--spacing-fm-lg",
    "--text-fm-lg",
    "--text-fm-sm",
  ],
}
