export const meta = {
  dependencies: {},
  devDependencies: {},
  internalDependencies: ["divider", "label", "chevron-right-icon", "tick-icon"],
  tokens: [
    "--color-fm-icon-active",
    "--color-fm-inactive",
    "--color-fm-label-secondary",
    "--color-fm-negative",
    "--color-fm-primary",
    "--color-fm-surface-frosted",
    "--color-fm-surface-negative",
    "--font-fm-brand",
    "--font-fm-text",
    "--gradient-fm-stroke-info",
    "--gradient-fm-stroke-negative",
    "--gradient-fm-stroke-neutral",
    "--gradient-fm-stroke-positive",
    "--gradient-fm-stroke-warning",
    "--leading-fm-lg",
    "--radius-fm-s",
    "--text-fm-lg",
  ],
}
