export const meta = {
  dependencies: {
    "@radix-ui/react-slider": "^1.3.5",
  },
  devDependencies: {},
  internalDependencies: [],
  tokens: [
    "--color-fm-blue-200",
    "--color-fm-blue-500",
    "--color-fm-green-200",
    "--color-fm-green-500",
    "--color-fm-neutral-200",
    "--color-fm-neutral-500",
    "--color-fm-primary",
    "--color-fm-primary-200",
    "--color-fm-primary-500",
    "--color-fm-secondary-200",
    "--color-fm-secondary-500",
    "--color-fm-yellow-200",
    "--color-fm-yellow-500",
    "--font-fm-brand",
    "--leading-fm-lg",
    "--leading-fm-md",
    "--leading-fm-sm",
    "--text-fm-lg",
    "--text-fm-md",
    "--text-fm-sm",
  ],
}
