#!/usr/bin/env node
import path from "path"
import chalk from "chalk"
import figlet from "figlet"
import fs from "fs-extra"
import inquirer from "inquirer"

import {
  CONFIG_FILE_NAME,
  DEFAULT_CONFIG,
  DEFAULT_CSS_FILE,
  PROJECT_NAME,
} from "../constants"
import { loadConfig } from "../utils"
import { convertToAuralUI } from "../utils/helpers"
import { figures } from "../utils/logger"
import {
  applyTheme,
  getAvailableThemes,
  processFontsForTheme,
} from "./helpers/theme-utils"

// Constants
const STYLES_DIR = path.resolve(__dirname, "./styles")
const CSS_HEADER = `/**
 * This file imports custom theme
 * Generated by ${PROJECT_NAME} CLI
 */

`

/**
 * Check if the project is initialized
 */
async function isProjectInitialized(): Promise<boolean> {
  const configPath = path.resolve(process.cwd(), CONFIG_FILE_NAME)
  return fs.pathExists(configPath)
}

/**
 * Select theme from available options
 */
async function selectTheme(availableThemes: string[]): Promise<string> {
  const { theme } = await inquirer.prompt([
    {
      type: "list",
      name: "theme",
      message: `${figures.bullet} Select a theme to use:`,
      choices: availableThemes,
      default: availableThemes[0],
      prefix: chalk.cyan("🎨"),
    },
  ])

  return theme
}

/**
 * Apply the selected theme to the CSS file
 */
async function applySelectedTheme(
  themeName: string,
  cssFile: string,
  config: typeof DEFAULT_CONFIG
): Promise<void> {
  const logSuccess = (message: string) => {
    console.log(chalk.green(`\n${figures.tick} ${message}\n`))
  }

  const logWarning = (message: string) => {
    console.log(chalk.cyan(`${figures.info} ${message}\n`))
  }

  const logError = (message: string) => {
    console.error(chalk.red(`${figures.cross} ${message}\n`))
  }

  // Use the utility function to apply the theme
  await applyTheme(
    themeName,
    cssFile,
    STYLES_DIR,
    logSuccess,
    logWarning,
    logError,
    CSS_HEADER
  )

  // Process fonts if configured
  if (config && config.fontDir) {
    await processFontsForTheme(themeName, cssFile, config)
  }
}

/**
 * Check if running in a CI or non-interactive environment
 */
function isNonInteractiveEnvironment(): boolean {
  return process.env.CI === "true" || !process.stdin.isTTY
}

/**
 * Main function to run the theme selection
 */
export async function runThemeSelection(
  themeName?: string,
  cssFilePath?: string
): Promise<void> {
  // Show a beautiful welcome message
  console.log(
    chalk.cyan(
      figlet.textSync(convertToAuralUI(PROJECT_NAME), {
        font: "Big",
        horizontalLayout: "full",
      })
    )
  )

  console.log(chalk.cyan(`\n${figures.pointer} Theme Selection Tool`))

  // Check if project is initialized
  if (!(await isProjectInitialized())) {
    console.error(
      chalk.red(
        `${figures.cross} Project not initialized. Run 'npx ${PROJECT_NAME} init' first.`
      )
    )
    return
  }

  const logWarning = (message: string) => {
    console.error(chalk.red(`${figures.cross} ${message}`))
  }

  const availableThemes = await getAvailableThemes(STYLES_DIR, logWarning)

  if (availableThemes.length === 0) {
    console.error(
      chalk.red(`${figures.cross} No theme files found in ${STYLES_DIR}`)
    )
    return
  }

  const config = await loadConfig()

  // Use provided theme name, or auto-select first theme in non-interactive environments
  let selectedTheme: string

  if (themeName && availableThemes.includes(themeName)) {
    // Use specified theme if valid
    selectedTheme = themeName
    console.log(
      chalk.cyan(
        `${figures.info} Using specified theme: ${chalk.bold(selectedTheme)}`
      )
    )
  } else if (isNonInteractiveEnvironment()) {
    // Auto-select first theme in non-interactive environments
    selectedTheme = config?.tailwind?.theme || availableThemes[0]
    console.log(
      chalk.cyan(
        `${
          figures.info
        } Non-interactive environment detected. Using default theme: ${chalk.bold(
          selectedTheme
        )}`
      )
    )
  } else {
    // Interactive selection
    selectedTheme = await selectTheme(availableThemes)
  }

  // Determine CSS file path

  const cssFile = cssFilePath || config?.tailwind?.css || DEFAULT_CSS_FILE

  await applySelectedTheme(selectedTheme, cssFile, config)

  console.log(
    chalk.cyan(
      `\n${figures.info} Theme ${chalk.bold(selectedTheme)} has been applied to your project.`
    )
  )
}
