export const meta = {
  dependencies: {},
  devDependencies: {},
  internalDependencies: ["feature-shine-icon"],
  tokens: [
    "--button-fm-background",
    "--button-fm-noise",
    "--color-fm-contrast",
    "--color-fm-divider-contrast",
    "--color-fm-inactive",
    "--color-fm-neutral-1100",
    "--color-fm-primary",
    "--color-fm-primary-200",
    "--color-fm-primary-600",
    "--color-fm-secondary-300",
    "--color-fm-secondary-800",
    "--color-fm-surface-secondary",
    "--font-fm-brand",
    "--spacing-fm-2xl",
    "--spacing-fm-4xl",
    "--spacing-fm-5xl",
    "--spacing-fm-lg",
    "--spacing-fm-xl",
    "--stroke-fm-sm",
    "--stroke-fm-xsm",
    "--text-fm-md",
    "--text-fm-sm",
    "--text-fm-xl",
    "--gradientSizeX",
    "--gradientSizeY",
    "--gradientPositionY",
  ],
}
