export const meta = {
  dependencies: {
    "@radix-ui/react-select": "^2.2.5",
  },
  devDependencies: {},
  internalDependencies: [
    "chevron-down-icon",
    "chevron-up-icon",
    "divider",
    "helper-text",
    "label",
    "tick-icon",
  ],
  tokens: [
    "--color-fm-divider-contrast",
    "--color-fm-divider-negative",
    "--color-fm-divider-positive",
    "--color-fm-divider-primary",
    "--color-fm-divider-tertiary",
    "--color-fm-divider-warning",
    "--color-fm-icon-active",
    "--color-fm-icon-inactive",
    "--color-fm-inactive",
    "--color-fm-placeholder",
    "--color-fm-primary",
    "--color-fm-surface-frosted",
    "--font-fm-text",
    "--gradient-fm-stroke-negative",
    "--gradient-fm-stroke-neutral",
    "--gradient-fm-stroke-positive",
    "--gradient-fm-stroke-warning",
    "--leading-fm-lg",
    "--leading-fm-md",
    "--leading-fm-xl",
    "--radius-fm-s",
    "--text-fm-lg",
    "--text-fm-md",
    "--text-fm-xl",
  ],
}
