export const meta = {
  dependencies: {
    "@radix-ui/react-dialog": "^1.1.14",
  },
  devDependencies: {},
  internalDependencies: ["cross-icon", "overlay"],
  tokens: [
    "--bottom-sheet-shadow",
    "--color-fm-primary",
    "--color-fm-blue-300",
    "--color-fm-button-fill-secondary",
    "--color-fm-divider-secondary",
    "--color-fm-green-300",
    "--color-fm-icon-active",
    "--color-fm-neutral-300",
    "--color-fm-red-300",
    "--color-fm-surface-frosted",
    "--color-fm-yellow-300",
    "--leading-fm-md",
    "--leading-fm-xl",
    "--left-sheet-shadow",
    "--radius-fm-s",
    "--right-sheet-shadow",
    "--text-fm-md",
    "--text-fm-xl",
    "--top-sheet-shadow",
    "--gradient-fm-stroke-positive",
    "--gradient-fm-stroke-negative",
    "--gradient-fm-stroke-warning",
    "--gradient-fm-stroke-info",
    "--gradient-fm-stroke-neutral",
    "--gradient-fm-stroke-positive-vertical",
    "--gradient-fm-stroke-negative-vertical",
    "--gradient-fm-stroke-warning-vertical",
    "--gradient-fm-stroke-info-vertical",
    "--gradient-fm-stroke-neutral-vertical",
  ],
}
